#include "SearchAlgorithm.h"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "BattleEmulator.h"
#include "lcg.h"

namespace SearchAlgorithm {
    namespace {
        constexpr int MAX_SEARCH_DEPTH = 349;
        constexpr size_t BASE_BEAM_WIDTH = 4096;
        constexpr size_t MAX_BEAM_WIDTH = 102400;

        // These are the ally actions implemented by the current BattleEmulator
        // and usable from the search-start state. Enemy actions are generated by
        // BattleEmulator itself and are never selected by the searcher.
        constexpr std::array<int32_t, 8> ACTIONS = {
            BattleEmulator::ATTACK_ALLY,
            BattleEmulator::DRAGON_SLASH,
            BattleEmulator::DEFENCE,
            BattleEmulator::HEAL,
            BattleEmulator::MEDICINAL_HERBS,
            BattleEmulator::ACROBATIC_STAR,
            BattleEmulator::CRACK_ALLY,
            BattleEmulator::FLEE_ALLY,
        };

        struct BeamState {
            State core{};
            std::array<uint8_t, MAX_SEARCH_DEPTH> actions{};
            int depth = 0;
        };

        struct Candidate {
            State core{};
            size_t parent = 0;
            uint8_t action = 0;
            int64_t quality = std::numeric_limits<int64_t>::min();
            int64_t lookahead = std::numeric_limits<int64_t>::min();
            uint64_t diversity = 0;
        };

        struct PassResult {
            BeamState state{};
            bool victory = false;
            bool timedOut = false;
            uint64_t expanded = 0;
        };

        struct SequenceCandidate {
            State core{};
            std::array<uint8_t, MAX_SEARCH_DEPTH> actions{};
            int depth = 0;
            int64_t score = std::numeric_limits<int64_t>::min();
            bool valid = false;
            bool victory = false;
        };

        uint64_t mix64(uint64_t value) {
            value += 0x9e3779b97f4a7c15ULL;
            value = (value ^ (value >> 30)) * 0xbf58476d1ce4e5b9ULL;
            value = (value ^ (value >> 27)) * 0x94d049bb133111ebULL;
            return value ^ (value >> 31);
        }

        int64_t resourceScore(const Player &ally) {
            return static_cast<int64_t>(ally.mp) * 32
                   + static_cast<int64_t>(ally.medicinal_herbs_count) * 96
                   + static_cast<int64_t>(ally.SpecialMedicineCount) * 16
                   + (ally.specialCharge ? 800 : 0)
                   + (ally.acrobaticStar ? 600 : 0);
        }

        int64_t qualityScore(const State &state) {
            const Player &ally = state.players[0];
            const Player &enemy = state.players[1];
            const int damage = enemy.maxHp - enemy.hp;

            int64_t score = static_cast<int64_t>(damage) * 8192
                            + static_cast<int64_t>(ally.hp) * 256
                            + resourceScore(ally);
            if (ally.hp <= 15) {
                score -= static_cast<int64_t>(16 - ally.hp) * 1400;
            }
            if (ally.paralysis) score -= 2200;
            if (ally.inactive) score -= 1800;
            if (enemy.rage) score -= 300;
            return score;
        }

        uint64_t diversityKey(const State &state, uint8_t action) {
            const Player &ally = state.players[0];
            const Player &enemy = state.players[1];
            uint64_t key = mix64(static_cast<uint64_t>(state.position));
            key ^= mix64(state.nowState);
            key ^= mix64(static_cast<uint64_t>(ally.hp) << 32 | static_cast<uint32_t>(enemy.hp));
            key ^= mix64(static_cast<uint64_t>(static_cast<uint32_t>(ally.mp)) << 32 |
                         static_cast<uint32_t>(ally.paralysisTurns));
            key ^= mix64(static_cast<uint64_t>(action) << 48 |
                         static_cast<uint64_t>(ally.specialCharge) << 40 |
                         static_cast<uint64_t>(ally.acrobaticStar) << 32 |
                         static_cast<uint32_t>(enemy.rageTurns));
            return key;
        }

        bool fleeIsSafeThisTurn(const State &state) {
            if (state.players[0].paralysis || state.players[0].inactive) return false;

            int position = state.position;
            const double allySpeed = state.players[0].speed * lcg::floatRand(&position, 0.51, 1.0);
            const double enemySpeed = state.players[1].speed * lcg::floatRand(&position, 0.51, 1.0);
            position++; // BattleEmulator.cpp:306
            if (allySpeed > enemySpeed) return true;

            // BattleEmulator.cpp:373 always consumes this roll. mitoreP is negative,
            // so the branch itself cannot fire in the current authoritative emulator.
            (void) lcg::getPercent(&position, 100);

            const int rnd = lcg::getPercent(&position, 0x100) + 1;
            int enemyAction;
            if (rnd <= 43) enemyAction = BattleEmulator::VICTIMISER;
            else if (rnd <= 43 + 42) enemyAction = BattleEmulator::HP_HOOVER;
            else if (rnd <= 43 + 42 + 43) enemyAction = BattleEmulator::CRACK_ENEMY;
            else if (rnd <= 43 + 42 + 43 + 43) enemyAction = BattleEmulator::ATTACK_ENEMY;
            else if (rnd <= 43 + 42 + 43 + 43 + 42) enemyAction = BattleEmulator::MANAZASHI;
            else enemyAction = BattleEmulator::PUFF_PUFF;

            if (enemyAction == BattleEmulator::MANAZASHI) {
                position += 2;
            } else if (!state.players[1].rage) {
                position++;
            }
            if (enemyAction == BattleEmulator::VICTIMISER) {
                enemyAction = BattleEmulator::HP_HOOVER;
            }
            position++; // BattleEmulator.cpp:404

            if (enemyAction == BattleEmulator::MANAZASHI) {
                position += 2;
                position++; // critical
                position++; // unrelated
                position++; // evade
                (void) lcg::floatRand(&position, -4.0, 4.0); // FUN_021e8458_typeD
                return lcg::getPercent(&position, 100) >= 25;
            }
            if (enemyAction == BattleEmulator::PUFF_PUFF) {
                position += 2;
                position++; // unrelated
                position++; // critical
                return lcg::getPercent(&position, 100) >= 50;
            }
            return true;
        }

        size_t legalActions(const State &state, std::array<size_t, ACTIONS.size()> &indices) {
            const Player &ally = state.players[0];
            size_t count = 0;

            // A supplied command is ignored by BattleEmulator while the ally is
            // unable to act. One representative input is enough for that forced
            // transition and avoids seven identical expansions.
            if (ally.paralysis || ally.inactive) {
                indices[count++] = 0;
                return count;
            }

            indices[count++] = 0; // Attack
            indices[count++] = 1; // Dragon Slash
            indices[count++] = 2; // Defence
            if (ally.mp >= 2) indices[count++] = 3; // Heal
            if (ally.medicinal_herbs_count > 0) indices[count++] = 4;
            if (ally.specialCharge && ally.specialChargeTurn >= 0) indices[count++] = 5;
            if (ally.mp >= 3) indices[count++] = 6; // Crack
            if (fleeIsSafeThisTurn(state)) indices[count++] = 7;
            return count;
        }

        int legalActionIndex(const State &state, uint8_t action) {
            std::array<size_t, ACTIONS.size()> legal{};
            const size_t legalCount = legalActions(state, legal);
            for (size_t i = 0; i < legalCount; ++i) {
                if (static_cast<uint8_t>(ACTIONS[legal[i]]) == action) {
                    return static_cast<int>(legal[i]);
                }
            }
            return -1;
        }

        uint64_t sequenceHash(const std::array<uint8_t, MAX_SEARCH_DEPTH> &actions, int depth) {
            uint64_t hash = 0xcbf29ce484222325ULL;
            for (int i = 0; i < depth; ++i) {
                hash ^= static_cast<uint64_t>(actions[i]) + static_cast<uint64_t>(i * 131);
                hash *= 0x100000001b3ULL;
            }
            return mix64(hash ^ static_cast<uint64_t>(depth));
        }

        BeamState materializeSequence(const SequenceCandidate &candidate) {
            BeamState result{};
            result.core = candidate.core;
            result.actions = candidate.actions;
            result.depth = candidate.depth;
            return result;
        }

        SequenceCandidate evaluateSequence(
                const State &startState,
                uint64_t seed,
                const std::array<uint8_t, MAX_SEARCH_DEPTH> &actions,
                int depth,
                const std::array<std::array<int32_t, 350>, ACTIONS.size()> &oneActionGenes,
                uint64_t &expanded) {
            SequenceCandidate candidate{};
            candidate.core = startState;
            candidate.actions = actions;
            candidate.depth = depth;

            for (int i = 0; i < depth; ++i) {
                int actionIndex;
                if (candidate.core.players[0].paralysis || candidate.core.players[0].inactive) {
                    // The supplied command is ignored by BattleEmulator on a
                    // forced turn. Canonicalize it to Attack instead of rejecting
                    // a sequence merely because the forced turn moved after a mutation.
                    actionIndex = 0;
                    candidate.actions[i] = static_cast<uint8_t>(BattleEmulator::ATTACK_ALLY);
                } else {
                    actionIndex = legalActionIndex(candidate.core, candidate.actions[i]);
                    if (actionIndex < 0) return candidate;
                }

                BattleEmulator::Main(&candidate.core.position, 1, oneActionGenes[actionIndex].data(),
                                     candidate.core.players, nullptr, seed, nullptr, nullptr, -2,
                                     &candidate.core.nowState, true);
                ++expanded;

                if (candidate.core.players[1].hp == 0) {
                    if (candidate.core.players[0].hp != 0) {
                        candidate.depth = i + 1;
                        candidate.victory = true;
                        candidate.valid = true;
                        candidate.score = (1LL << 60)
                                          + static_cast<int64_t>(candidate.core.players[0].hp) * 1024
                                          + resourceScore(candidate.core.players[0]);
                    }
                    return candidate;
                }
                if (candidate.core.players[0].hp == 0) return candidate;
            }

            candidate.valid = true;
            candidate.score = qualityScore(candidate.core);
            return candidate;
        }

        PassResult localCompress(const State &startState,
                                 uint64_t seed,
                                 const BeamState &incumbent,
                                 std::chrono::steady_clock::time_point deadline) {
            PassResult result{};
            result.state.core = startState;
            const int targetDepth = incumbent.depth - 1;
            if (targetDepth <= 0) return result;

            std::array<std::array<int32_t, 350>, ACTIONS.size()> oneActionGenes{};
            for (size_t i = 0; i < ACTIONS.size(); ++i) {
                oneActionGenes[i][0] = ACTIONS[i];
                oneActionGenes[i][1] = -1;
            }
            lcg::init(seed, true);

            constexpr size_t POPULATION = 96;
            constexpr int GENERATIONS = 1;
            std::vector<SequenceCandidate> population;
            population.reserve(std::max<size_t>(POPULATION * 2, static_cast<size_t>(incumbent.depth)));

            SequenceCandidate bestPartial{};
            bool havePartial = false;
            auto consider = [&](SequenceCandidate &&candidate) -> bool {
                if (!candidate.valid) return false;
                if (candidate.victory) {
                    result.state = materializeSequence(candidate);
                    result.victory = true;
                    return true;
                }
                if (!havePartial || candidate.score > bestPartial.score) {
                    bestPartial = candidate;
                    havePartial = true;
                }
                population.push_back(std::move(candidate));
                return false;
            };

            // Seed the target-depth population by deleting each single action
            // from the incumbent discovered by the search itself. This is a
            // generic incumbent-compression move, not an externally supplied
            // witness or input-specific hint.
            for (int drop = 0; drop < incumbent.depth; ++drop) {
                std::array<uint8_t, MAX_SEARCH_DEPTH> actions{};
                int out = 0;
                for (int i = 0; i < incumbent.depth; ++i) {
                    if (i != drop) actions[out++] = incumbent.actions[i];
                }
                SequenceCandidate candidate = evaluateSequence(startState, seed, actions, targetDepth,
                                                                oneActionGenes, result.expanded);
                if (consider(std::move(candidate))) return result;
                if (std::chrono::steady_clock::now() >= deadline) {
                    result.timedOut = true;
                    if (havePartial) result.state = materializeSequence(bestPartial);
                    return result;
                }
            }

            auto trimPopulation = [&]() {
                if (population.size() <= POPULATION) return;
                std::nth_element(population.begin(), population.begin() + static_cast<std::ptrdiff_t>(POPULATION),
                                 population.end(), [](const SequenceCandidate &a, const SequenceCandidate &b) {
                                     if (a.score != b.score) return a.score > b.score;
                                     if (a.core.players[1].hp != b.core.players[1].hp) {
                                         return a.core.players[1].hp < b.core.players[1].hp;
                                     }
                                     return a.core.players[0].hp > b.core.players[0].hp;
                                 });
                population.resize(POPULATION);
            };
            trimPopulation();

            for (int generation = 0; generation < GENERATIONS && !population.empty(); ++generation) {
                std::vector<SequenceCandidate> next = population;
                next.reserve(POPULATION * 16);
                std::unordered_set<uint64_t> seen;
                seen.reserve(POPULATION * 32);
                for (const SequenceCandidate &candidate : population) {
                    seen.insert(sequenceHash(candidate.actions, targetDepth));
                }

                for (const SequenceCandidate &parent : population) {
                    for (int pos = 0; pos < targetDepth; ++pos) {
                        for (int32_t action : ACTIONS) {
                            const uint8_t encoded = static_cast<uint8_t>(action);
                            if (parent.actions[pos] == encoded) continue;

                            auto actions = parent.actions;
                            actions[pos] = encoded;
                            if (!seen.insert(sequenceHash(actions, targetDepth)).second) continue;

                            SequenceCandidate candidate = evaluateSequence(startState, seed, actions, targetDepth,
                                                                            oneActionGenes, result.expanded);
                            if (!candidate.valid) continue;
                            if (candidate.victory) {
                                result.state = materializeSequence(candidate);
                                result.victory = true;
                                return result;
                            }
                            if (!havePartial || candidate.score > bestPartial.score) {
                                bestPartial = candidate;
                                havePartial = true;
                            }
                            next.push_back(std::move(candidate));
                        }
                        if (std::chrono::steady_clock::now() >= deadline) {
                            result.timedOut = true;
                            if (havePartial) result.state = materializeSequence(bestPartial);
                            return result;
                        }
                    }
                }
                population.swap(next);
                trimPopulation();
            }

            // Spend the remaining local-search slice on broader deterministic
            // multi-point mutations. This deliberately jumps between RNG phases
            // instead of repeatedly polishing only the one-edit neighborhood.
            uint64_t rng = mix64(seed ^ incumbent.core.nowState
                                 ^ static_cast<uint64_t>(incumbent.core.position)
                                 ^ (static_cast<uint64_t>(targetDepth) << 32));
            uint64_t trials = 0;
            while (!population.empty() && std::chrono::steady_clock::now() < deadline) {
                rng = mix64(rng + 0x9e3779b97f4a7c15ULL + trials++);
                const SequenceCandidate &parent = population[rng % population.size()];
                auto actions = parent.actions;
                const int mutationCount = 1 + static_cast<int>((rng >> 8) & 3ULL);
                uint64_t bits = rng;
                for (int mutation = 0; mutation < mutationCount; ++mutation) {
                    bits = mix64(bits + static_cast<uint64_t>(mutation + 1));
                    const int pos = static_cast<int>(bits % static_cast<uint64_t>(targetDepth));
                    const size_t actionIndex = static_cast<size_t>((bits >> 16) % ACTIONS.size());
                    actions[pos] = static_cast<uint8_t>(ACTIONS[actionIndex]);
                }

                SequenceCandidate candidate = evaluateSequence(startState, seed, actions, targetDepth,
                                                                oneActionGenes, result.expanded);
                if (!candidate.valid) continue;
                if (candidate.victory) {
                    result.state = materializeSequence(candidate);
                    result.victory = true;
                    return result;
                }
                if (!havePartial || candidate.score > bestPartial.score) {
                    bestPartial = candidate;
                    havePartial = true;
                }
                population.push_back(std::move(candidate));
                if (population.size() >= POPULATION * 8) trimPopulation();
            }
            trimPopulation();

            if (std::chrono::steady_clock::now() >= deadline) result.timedOut = true;
            if (havePartial) result.state = materializeSequence(bestPartial);
            return result;
        }

        BeamState materialize(const BeamState &parent, const Candidate &candidate) {
            BeamState child{};
            child.core = candidate.core;
            child.actions = parent.actions;
            child.actions[parent.depth] = candidate.action;
            child.depth = parent.depth + 1;
            return child;
        }

        bool betterCoreResult(const State &lhs, int lhsDepth, const BeamState &rhs) {
            const Player &la = lhs.players[0];
            const Player &le = lhs.players[1];
            const Player &ra = rhs.core.players[0];
            const Player &re = rhs.core.players[1];
            if (le.hp != re.hp) return le.hp < re.hp;
            if (la.hp != ra.hp) return la.hp > ra.hp;
            const int64_t lr = resourceScore(la);
            const int64_t rr = resourceScore(ra);
            if (lr != rr) return lr > rr;
            return lhsDepth < rhs.depth;
        }

        template <typename Better>
        void appendQuota(const std::vector<Candidate> &candidates,
                         std::vector<uint8_t> &selectedFlags,
                         std::vector<size_t> &selected,
                         size_t beamWidth,
                         size_t count,
                         Better better) {
            if (count == 0 || selected.size() >= beamWidth) return;
            count = std::min(count, beamWidth - selected.size());

            std::vector<size_t> pool;
            pool.reserve(candidates.size() - selected.size());
            for (size_t i = 0; i < candidates.size(); ++i) {
                if (!selectedFlags[i]) pool.push_back(i);
            }
            if (pool.empty()) return;

            count = std::min(count, pool.size());
            if (count < pool.size()) {
                std::nth_element(pool.begin(), pool.begin() + static_cast<std::ptrdiff_t>(count), pool.end(),
                                 [&](size_t lhs, size_t rhs) {
                                     return better(candidates[lhs], candidates[rhs]);
                                 });
                pool.resize(count);
            }

            for (size_t index : pool) {
                selectedFlags[index] = 1;
                selected.push_back(index);
            }
        }

        template <typename Better>
        void appendActionQuota(const std::vector<Candidate> &candidates,
                               std::vector<uint8_t> &selectedFlags,
                               std::vector<size_t> &selected,
                               size_t beamWidth,
                               size_t count,
                               uint8_t action,
                               Better better) {
            if (count == 0 || selected.size() >= beamWidth) return;
            count = std::min(count, beamWidth - selected.size());

            std::vector<size_t> pool;
            pool.reserve(count * 2);
            for (size_t i = 0; i < candidates.size(); ++i) {
                if (!selectedFlags[i] && candidates[i].action == action) pool.push_back(i);
            }
            if (pool.empty()) return;

            count = std::min(count, pool.size());
            if (count < pool.size()) {
                std::nth_element(pool.begin(), pool.begin() + static_cast<std::ptrdiff_t>(count), pool.end(),
                                 [&](size_t lhs, size_t rhs) {
                                     return better(candidates[lhs], candidates[rhs]);
                                 });
                pool.resize(count);
            }
            for (size_t index : pool) {
                selectedFlags[index] = 1;
                selected.push_back(index);
            }
        }

        void appendPhaseQuota(std::vector<Candidate> &candidates,
                              std::vector<uint8_t> &selectedFlags,
                              std::vector<size_t> &selected,
                              size_t beamWidth,
                              size_t count,
                              uint64_t seed,
                              const std::array<std::array<int32_t, 350>, ACTIONS.size()> &oneActionGenes,
                              uint64_t &expanded,
                              std::chrono::steady_clock::time_point deadline) {
            if (count == 0 || selected.size() >= beamWidth) return;
            count = std::min(count, beamWidth - selected.size());

            std::unordered_map<uint64_t, size_t> bestByPhase;
            bestByPhase.reserve(std::min(candidates.size(), count * 4));
            for (size_t i = 0; i < candidates.size(); ++i) {
                if (selectedFlags[i]) continue;
                const Candidate &candidate = candidates[i];
                const uint64_t phase = static_cast<uint64_t>(candidate.core.position)
                                       | ((candidate.core.nowState & 0xfffULL) << 16)
                                       | (static_cast<uint64_t>(candidate.core.players[0].paralysis) << 28)
                                       | (static_cast<uint64_t>(candidate.core.players[0].inactive) << 29)
                                       | (static_cast<uint64_t>(candidate.core.players[0].acrobaticStar) << 30);
                const auto it = bestByPhase.find(phase);
                if (it == bestByPhase.end() || candidate.quality > candidates[it->second].quality) {
                    bestByPhase[phase] = i;
                }
            }

            std::vector<size_t> pool;
            pool.reserve(bestByPhase.size());
            for (const auto &[phase, index] : bestByPhase) {
                (void) phase;
                pool.push_back(index);
            }
            if (pool.empty()) return;
            count = std::min(count, pool.size());

            // Only probe a bounded superset of the quota. Current quality gets
            // us into the right neighborhood; one authoritative extra turn then
            // spots RNG phases whose payoff is delayed until the next attack.
            const size_t probeCount = std::min(pool.size(), count * 3);
            if (probeCount < pool.size()) {
                std::nth_element(pool.begin(), pool.begin() + static_cast<std::ptrdiff_t>(probeCount), pool.end(),
                                 [&](size_t lhs, size_t rhs) {
                                     return candidates[lhs].quality > candidates[rhs].quality;
                                 });
                pool.resize(probeCount);
            }

            for (size_t index : pool) candidates[index].lookahead = candidates[index].quality;
            for (size_t index : pool) {
                if ((expanded & 255ULL) == 0 && std::chrono::steady_clock::now() >= deadline) break;
                Candidate &candidate = candidates[index];
                int64_t bestFuture = candidate.quality;
                const bool forced = candidate.core.players[0].paralysis || candidate.core.players[0].inactive;
                const int probes = forced ? 1 : 2;
                for (int probe = 0; probe < probes; ++probe) {
                    State future = candidate.core;
                    const size_t actionIndex = static_cast<size_t>(probe); // Attack, Dragon Slash
                    BattleEmulator::Main(&future.position, 1, oneActionGenes[actionIndex].data(),
                                         future.players, nullptr, seed, nullptr, nullptr, -2,
                                         &future.nowState, true);
                    ++expanded;
                    if (future.players[1].hp == 0 && future.players[0].hp != 0) {
                        bestFuture = std::max(bestFuture,
                                              (1LL << 60)
                                              + static_cast<int64_t>(future.players[0].hp) * 1024
                                              + resourceScore(future.players[0]));
                    } else if (future.players[0].hp != 0) {
                        bestFuture = std::max(bestFuture, qualityScore(future));
                    }
                }
                candidate.lookahead = bestFuture;
            }

            if (count < pool.size()) {
                std::nth_element(pool.begin(), pool.begin() + static_cast<std::ptrdiff_t>(count), pool.end(),
                                 [&](size_t lhs, size_t rhs) {
                                     if (candidates[lhs].lookahead != candidates[rhs].lookahead) {
                                         return candidates[lhs].lookahead > candidates[rhs].lookahead;
                                     }
                                     return candidates[lhs].quality > candidates[rhs].quality;
                                 });
                pool.resize(count);
            }
            for (size_t index : pool) {
                selectedFlags[index] = 1;
                selected.push_back(index);
            }
        }

        std::vector<size_t> selectCandidates(std::vector<Candidate> &candidates,
                                             size_t beamWidth,
                                             uint64_t seed,
                                             const std::array<std::array<int32_t, 350>, ACTIONS.size()> &oneActionGenes,
                                             uint64_t &expanded,
                                             std::chrono::steady_clock::time_point deadline) {
            std::vector<size_t> selected;
            selected.reserve(std::min(beamWidth, candidates.size()));
            if (candidates.size() <= beamWidth) {
                for (size_t i = 0; i < candidates.size(); ++i) selected.push_back(i);
                return selected;
            }

            std::vector<uint8_t> flags(candidates.size(), 0);
            // Survival and resources are already priced into qualityScore. Keeping
            // separate full-candidate quotas for them costs two extra O(N) scans
            // and nth_element passes per layer, reducing the number of exact
            // BattleEmulator transitions we can examine inside the fixed budget.
            appendQuota(candidates, flags, selected, beamWidth, beamWidth * 65 / 100,
                        [](const Candidate &a, const Candidate &b) {
                            if (a.quality != b.quality) return a.quality > b.quality;
                            if (a.core.players[1].hp != b.core.players[1].hp) {
                                return a.core.players[1].hp < b.core.players[1].hp;
                            }
                            return a.core.players[0].hp > b.core.players[0].hp;
                        });

            appendActionQuota(candidates, flags, selected, beamWidth, beamWidth * 10 / 100,
                              static_cast<uint8_t>(BattleEmulator::FLEE_ALLY),
                              [](const Candidate &a, const Candidate &b) {
                                  if (a.core.players[1].hp != b.core.players[1].hp) {
                                      return a.core.players[1].hp < b.core.players[1].hp;
                                  }
                                  if (a.core.players[0].hp != b.core.players[0].hp) {
                                      return a.core.players[0].hp > b.core.players[0].hp;
                                  }
                                  return a.diversity > b.diversity;
                              });

            appendPhaseQuota(candidates, flags, selected, beamWidth, beamWidth * 15 / 100,
                             seed, oneActionGenes, expanded, deadline);

            appendQuota(candidates, flags, selected, beamWidth, beamWidth - selected.size(),
                        [](const Candidate &a, const Candidate &b) {
                            return a.diversity > b.diversity;
                        });
            return selected;
        }

        PassResult runPass(const State &startState,
                           uint64_t seed,
                           int maxDepth,
                           size_t beamWidth,
                           std::chrono::steady_clock::time_point deadline) {
            PassResult pass{};
            pass.state.core = startState;
            if (maxDepth <= 0 || startState.players[0].hp == 0 || startState.players[1].hp == 0) {
                pass.victory = startState.players[1].hp == 0 && startState.players[0].hp != 0;
                return pass;
            }

            std::array<std::array<int32_t, 350>, ACTIONS.size()> oneActionGenes{};
            for (size_t i = 0; i < ACTIONS.size(); ++i) {
                oneActionGenes[i][0] = ACTIONS[i];
                oneActionGenes[i][1] = -1;
            }

            lcg::init(seed, true);
            std::vector<BeamState> beam;
            beam.reserve(beamWidth);
            beam.push_back(pass.state);

            for (int layer = 0; layer < maxDepth && !beam.empty(); ++layer) {
                std::vector<Candidate> candidates;
                candidates.reserve(beam.size() * ACTIONS.size());
                bool haveWinner = false;
                BeamState bestWinner{};

                for (size_t parentIndex = 0; parentIndex < beam.size() && !pass.timedOut; ++parentIndex) {
                    const BeamState &parent = beam[parentIndex];
                    std::array<size_t, ACTIONS.size()> legal{};
                    const size_t legalCount = legalActions(parent.core, legal);

                    for (size_t legalIndex = 0; legalIndex < legalCount; ++legalIndex) {
                        const size_t actionIndex = legal[legalIndex];
                        Candidate candidate{};
                        candidate.core = parent.core;
                        candidate.parent = parentIndex;
                        candidate.action = static_cast<uint8_t>(ACTIONS[actionIndex]);

                        BattleEmulator::Main(&candidate.core.position, 1, oneActionGenes[actionIndex].data(),
                                             candidate.core.players, nullptr, seed, nullptr, nullptr, -2,
                                             &candidate.core.nowState, true);
                        ++pass.expanded;
                        candidate.quality = qualityScore(candidate.core);
                        candidate.diversity = diversityKey(candidate.core, candidate.action);

                        if (candidate.core.players[1].hp == 0 && candidate.core.players[0].hp != 0) {
                            if (!haveWinner || betterCoreResult(candidate.core, parent.depth + 1, bestWinner)) {
                                bestWinner = materialize(parent, candidate);
                                haveWinner = true;
                            }
                        } else if (candidate.core.players[0].hp != 0) {
                            if (betterCoreResult(candidate.core, parent.depth + 1, pass.state)) {
                                pass.state = materialize(parent, candidate);
                            }
                            candidates.push_back(candidate);
                        }

                        if ((pass.expanded & 1023ULL) == 0 && std::chrono::steady_clock::now() >= deadline) {
                            pass.timedOut = true;
                            break;
                        }
                    }
                }

                if (haveWinner) {
                    pass.state = bestWinner;
                    pass.victory = true;
                    return pass;
                }
                if (pass.timedOut || candidates.empty()) return pass;

                const std::vector<size_t> selected = selectCandidates(candidates, beamWidth, seed,
                                                                      oneActionGenes, pass.expanded, deadline);
                std::vector<BeamState> nextBeam;
                nextBeam.reserve(selected.size());
                for (size_t index : selected) {
                    const Candidate &candidate = candidates[index];
                    nextBeam.push_back(materialize(beam[candidate.parent], candidate));
                }
                beam.swap(nextBeam);

                if (std::chrono::steady_clock::now() >= deadline) {
                    pass.timedOut = true;
                    return pass;
                }
            }
            return pass;
        }

        State replay(const State &startState, uint64_t seed, const BeamState &state) {
            State replayed = startState;
            lcg::init(seed, true);
            std::array<int32_t, 350> oneAction{};
            oneAction[1] = -1;
            for (int i = 0; i < state.depth; ++i) {
                oneAction[0] = state.actions[i];
                BattleEmulator::Main(&replayed.position, 1, oneAction.data(), replayed.players,
                                     nullptr, seed, nullptr, nullptr, -2, &replayed.nowState, true);
            }
            return replayed;
        }

        Result finishResult(const State &startState,
                            uint64_t seed,
                            const BeamState &state,
                            bool timedOut,
                            uint64_t expanded,
                            std::chrono::steady_clock::time_point started) {
            Result result{};
            result.actionCount = state.depth;
            for (int i = 0; i < state.depth; ++i) result.actions[i] = state.actions[i];
            result.timedOut = timedOut;
            result.expanded = expanded;
            result.finalState = replay(startState, seed, state);
            result.victory = result.finalState.players[1].hp == 0 && result.finalState.players[0].hp != 0;
            const auto ended = std::chrono::steady_clock::now();
            result.elapsedMs = std::chrono::duration<double, std::milli>(ended - started).count();
            return result;
        }
    }

    Result Run(const State &startState, uint64_t seed, int absoluteStartTurn, int budgetMs) {
        const auto started = std::chrono::steady_clock::now();
        const int guardedBudgetMs = std::max(1, budgetMs - 75);
        const auto deadline = started + std::chrono::milliseconds(guardedBudgetMs);
        if (startState.players[1].hp == 0 || startState.players[0].hp == 0) {
            BeamState best{};
            best.core = startState;
            return finishResult(startState, seed, best, false, 0, started);
        }

        const int maxDepth = std::min(MAX_SEARCH_DEPTH, 349 - absoluteStartTurn);
        BeamState empty{};
        empty.core = startState;
        if (maxDepth <= 0) return finishResult(startState, seed, empty, false, 0, started);

        PassResult baseline = runPass(startState, seed, maxDepth, BASE_BEAM_WIDTH, deadline);
        uint64_t totalExpanded = baseline.expanded;
        BeamState best = baseline.state;
        bool haveVictory = baseline.victory;

        if (!haveVictory || baseline.timedOut || best.depth <= 1) {
            return finishResult(startState, seed, best, baseline.timedOut, totalExpanded, started);
        }

        // Before spending the rest of the budget on a much wider beam, try to
        // compress the incumbent by one turn. A short exact local search around
        // a solution found in this same request is cheap and often exposes RNG-
        // phase improvements that a damage-first beam would otherwise prune.
        for (int compressionAttempt = 0; compressionAttempt < 2 && best.depth > 1; ++compressionAttempt) {
            const auto now = std::chrono::steady_clock::now();
            if (now >= deadline) break;
            const double remainingMs = std::chrono::duration<double, std::milli>(deadline - now).count();
            const int sliceMs = static_cast<int>(std::clamp(remainingMs * 0.20, 80.0, 325.0));
            const auto localDeadline = std::min(deadline, now + std::chrono::milliseconds(sliceMs));
            PassResult compressed = localCompress(startState, seed, best, localDeadline);
            totalExpanded += compressed.expanded;
            if (!compressed.victory || compressed.state.depth >= best.depth) break;
            best = compressed.state;
            haveVictory = true;
        }

        size_t previousWidth = BASE_BEAM_WIDTH;
        size_t lastCompletedWidth = 0;
        int lastCompletedDepth = 0;
        double lastCompletedMs = 0.0;
        while (std::chrono::steady_clock::now() < deadline && best.depth > 1) {
            const auto now = std::chrono::steady_clock::now();
            const double usedMs = std::max(0.01,
                std::chrono::duration<double, std::milli>(now - started).count());
            const double remainingMs = std::chrono::duration<double, std::milli>(deadline - now).count();
            if (remainingMs <= 1.0) break;

            const int targetDepth = best.depth - 1;
            size_t nextWidth = 0;
            if (lastCompletedWidth != 0 && lastCompletedMs > 0.0) {
                const double depthScale = static_cast<double>(lastCompletedDepth) / targetDepth;
                const double safeWidth = static_cast<double>(lastCompletedWidth)
                                         * (remainingMs / lastCompletedMs)
                                         * depthScale
                                         * 0.88;
                const double growthCap = static_cast<double>(previousWidth) * 2.0;
                nextWidth = static_cast<size_t>(std::min(growthCap, safeWidth));
                if (nextWidth <= previousWidth + 1024) break;
            } else {
                const double estimatedWidth = static_cast<double>(BASE_BEAM_WIDTH)
                                              * (remainingMs / usedMs)
                                              * (static_cast<double>(best.depth) / targetDepth)
                                              * 0.92;
                nextWidth = static_cast<size_t>(std::max<double>(previousWidth * 2.0, estimatedWidth));
            }
            nextWidth = std::min(nextWidth, MAX_BEAM_WIDTH);
            if (nextWidth <= previousWidth) break;

            const auto passStarted = std::chrono::steady_clock::now();
            PassResult wider = runPass(startState, seed, targetDepth, nextWidth, deadline);
            const auto passEnded = std::chrono::steady_clock::now();
            const double passMs = std::max(0.01,
                std::chrono::duration<double, std::milli>(passEnded - passStarted).count());
            totalExpanded += wider.expanded;
            previousWidth = nextWidth;
            if (!wider.timedOut) {
                lastCompletedWidth = nextWidth;
                lastCompletedDepth = targetDepth;
                lastCompletedMs = passMs;
            }
            if (wider.victory) {
                best = wider.state;
                haveVictory = true;
            }
            if (wider.timedOut || nextWidth == MAX_BEAM_WIDTH) break;
        }

        return finishResult(startState, seed, best, std::chrono::steady_clock::now() >= deadline,
                            totalExpanded, started);
    }
}
